version: '3'

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "log_lock_waits=on"]
    networks:
      - insopesca

  web:
    build: .
    env_file: ./.env
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - insopesca
  
  redis:
    image: redis
    networks: 
      - insopesca

networks:
  insopesca:
    driver: bridge
