version: '3'

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - insopesca

  web:
    build: .
    env_file: ./.env
    command: ./run_server.sh
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - insopesca

  redis:
    image: redis
    networks: 
      - insopesca

  server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./static:/opt/services/web/static
      - ./media:/opt/services/web/media
    networks:
      - insopesca
    depends_on:
      - web

networks:
  insopesca:
    driver: bridge
