version: '3'

services:
  web:
    build: .
    env_file: ./.env
    command: ./manage.py runserver 0.0.0.0:8000 --settings=insopesca.local_settings
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    networks:
      - insopesca


networks:
  insopesca:
    driver: bridge
