# Generated by Django 2.1 on 2019-04-20 18:50

from django.db import migrations, models
import utils.users_exists


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.CharField(max_length=15, unique=True, validators=[utils.users_exists.user_exists], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
