# Generated by Django 2.1 on 2019-02-10 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sex', models.CharField(choices=[('is_male', 'Masculino'), ('is_female', 'Femenino')], max_length=15, verbose_name='Sexo')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Elimanido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('G', 'G'), ('J', 'J'), ('C', 'C'), ('P', 'P')], max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_permission', models.CharField(max_length=30, verbose_name='Codigo del Permiso')),
                ('cod_register_mercantil', models.CharField(max_length=30, verbose_name='Codigo de Registro Mercantil')),
                ('account', models.ManyToManyField(to='sanidad.Account', verbose_name='Encargados')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality', verbose_name='Municipio')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parish', verbose_name='Parroquia')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='Estado')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sex', models.CharField(choices=[('is_male', 'Masculino'), ('is_female', 'Femenino')], max_length=15, verbose_name='Sexo')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Elimanido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20, verbose_name='Tipo')),
                ('registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matricula')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('load_capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Capacidad de Carga')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('year_vessel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Año De Embarcación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ManyToManyField(to='sanidad.Driver', verbose_name='Condutores')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='transport',
            field=models.ManyToManyField(to='sanidad.Transport', verbose_name='Transporte'),
        ),
    ]
