# Generated by Django 2.1 on 2019-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sex', models.CharField(choices=[('is_male', 'Masculino'), ('is_female', 'Femenino')], max_length=15, verbose_name='Sexo')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('G', 'G'), ('J', 'J'), ('C', 'C'), ('P', 'P')], max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speg', models.CharField(max_length=4, verbose_name='SPES')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality', verbose_name='Municipio')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parish', verbose_name='Parroquia')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='Estado')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyHasAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sex', models.CharField(choices=[('is_male', 'Masculino'), ('is_female', 'Femenino')], max_length=15, verbose_name='Sexo')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_account_id', models.UUIDField()),
                ('date', models.DateField(verbose_name='Fecha de la Inspección')),
                ('result', models.CharField(choices=[('is_verygood', 'Muy Bueno'), ('is_good', 'Bueno'), ('is_bad', 'Malo')], max_length=15, verbose_name='Resultados')),
                ('next_date', models.DateField(verbose_name='Fecha de la siguiente Inspección')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('company_driver_id', models.UUIDField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('is_land', 'Terrestre'), ('is_maritime', 'Maritimo'), ('is_fluvial', 'Fluvial')], max_length=20, verbose_name='Tipo')),
                ('registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matricula')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('load_capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Capacidad de Carga')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('year_vessel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Año De Embarcación')),
                ('name_fluvial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('type_vessel', models.CharField(blank=True, choices=[('Curiara', 'Curiara'), ('Canoa', 'Canoa')], max_length=20, null=True, verbose_name='Tipo De Embarcación')),
                ('result', models.CharField(blank=True, max_length=9999, null=True, verbose_name='Resultado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_driver_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.TypeCompany', verbose_name='Tipo De Compañia'),
        ),
    ]
