# Generated by Django 2.1 on 2019-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='transport',
        ),
        migrations.AddField(
            model_name='transport',
            name='company',
            field=models.ManyToManyField(to='sanidad.Company', verbose_name='Empresas'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_document',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=2, verbose_name='Tipo De Documento'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='type_document',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=2, verbose_name='Tipo De Documento'),
        ),
    ]
