# Generated by Django 2.1 on 2019-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
    ]
