# Generated by Django 2.1 on 2019-03-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='speg',
            field=models.CharField(max_length=4, verbose_name='SPES'),
        ),
    ]
