# Generated by Django 2.1 on 2019-02-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_auto_20190226_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='speg',
            field=models.CharField(max_length=4, verbose_name='SPEG'),
        ),
    ]
