# Generated by Django 2.1 on 2019-03-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_auto_20190318_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='name_fluvial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='transport',
            name='result',
            field=models.CharField(blank=True, max_length=9999, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='transport',
            name='type_vessel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo De Embarcación'),
        ),
    ]
