# Generated by Django 2.1 on 2019-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_auto_20190217_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='transport',
            field=models.ManyToManyField(to='sanidad.Transport', verbose_name='Conductor'),
        ),
    ]
