# Generated by Django 2.1 on 2019-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_auto_20190210_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Direccion'),
        ),
    ]
