# Generated by Django 2.1 on 2019-03-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_company_is_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_inspection',
            field=models.BooleanField(default=False),
        ),
    ]
