# Generated by Django 2.1 on 2019-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0003_auto_20190319_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('is_land', 'Terrestre'), ('is_maritime', 'Maritimo'), ('is_fluvial', 'Fluvial')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_vessel',
            field=models.CharField(blank=True, choices=[('Curiara', 'Curiara'), ('Canoa', 'Canoa')], max_length=20, null=True, verbose_name='Tipo De Embarcación'),
        ),
    ]
