# Generated by Django 2.1 on 2019-02-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0004_auto_20190226_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Inspección')),
                ('next_date', models.DateField(verbose_name='Fecha de la siguiente Inspección')),
                ('result', models.CharField(choices=[('is_verygood', 'Muy Bueno'), ('is_good', 'Bueno'), ('is_bad', 'Malo')], max_length=15, verbose_name='Resultados')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.Company')),
            ],
        ),
    ]
