# Generated by Django 2.1 on 2019-02-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0005_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.Company', verbose_name='Compañia'),
        ),
    ]
