# Generated by Django 2.1 on 2019-02-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0006_auto_20190226_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ('-created_at',)},
        ),
    ]
