# Generated by Django 2.1 on 2019-01-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lagoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagoon_diameter', models.IntegerField(verbose_name='Diametro de la Laguna')),
                ('lagoon_deepth', models.IntegerField(verbose_name='Profundidad de la Laguna ')),
                ('total_area_mirror_guater', models.IntegerField(verbose_name='Area total de Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CEDULA', 'CEDULA'), ('PASAPORTE', 'PASAPORTE'), ('RIF', 'RIF')], max_length=50, verbose_name='Tipo de Documento')),
                ('document', models.CharField(max_length=10, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('landline', models.CharField(max_length=11, verbose_name='Telefono Fijo')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('parish', models.CharField(max_length=11, verbose_name='Parroquia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_name', models.CharField(max_length=50, verbose_name='Nombre Ordinario')),
                ('scientific_name', models.CharField(max_length=50, verbose_name='Nombre Cientifico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_diameter', models.IntegerField(verbose_name='Diametro del Pozo')),
                ('well_deepth', models.IntegerField(verbose_name='Profundidad del Pozo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Production_unit')),
            ],
        ),
        migrations.AddField(
            model_name='lagoon',
            name='producion_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Production_unit'),
        ),
    ]
