# Generated by Django 2.1 on 2019-02-10 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinal_point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('north', models.IntegerField(verbose_name='Norte')),
                ('south', models.IntegerField(verbose_name='Sur')),
                ('west', models.IntegerField(verbose_name='Este')),
                ('oest', models.IntegerField(verbose_name='Oeste')),
                ('altitude', models.IntegerField(verbose_name='Altitud')),
                ('total_area_terr', models.IntegerField(verbose_name='Area total del Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lagoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lagoon_diameter', models.IntegerField(verbose_name='Diametro de la Laguna')),
                ('lagoon_deepth', models.IntegerField(verbose_name='Profundidad de la Laguna ')),
                ('total_area_mirror_guater', models.IntegerField(verbose_name='Area total de Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lagoon_tracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lagoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('G', 'G'), ('J', 'J'), ('C', 'C'), ('P', 'P')], max_length=2, verbose_name='Tipo De Documento')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Documento')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('tlf', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('tlf_house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono Casa')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality', verbose_name='Municipio')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parish', verbose_name='Parroquia')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='Estado')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repre_unit_productive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document_repre', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('G', 'G'), ('J', 'J'), ('C', 'C'), ('P', 'P')], max_length=50, verbose_name='Tipo de Documento')),
                ('document_repre', models.CharField(max_length=10, unique=True, verbose_name='Documento')),
                ('name_repre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name_repre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('landline_repre', models.CharField(max_length=11, verbose_name='Telefono Fijo')),
                ('phone_repre', models.CharField(max_length=11, verbose_name='Telefono Movil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_name', models.CharField(max_length=50, verbose_name='Nombre Ordinario')),
                ('scientific_name', models.CharField(max_length=50, verbose_name='Nombre Cientifico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_lagoon', models.IntegerField(verbose_name='Numero de Lagunas')),
                ('new_number_lagoon', models.IntegerField(verbose_name='Numero de Nuevas de Lagunas')),
                ('number_well', models.IntegerField(verbose_name='Numero de Pozos')),
                ('new_number_well', models.IntegerField(verbose_name='Numero de  Nuevos Pozos ')),
                ('illegal_superfaces', models.IntegerField(verbose_name='Numero de Superficies Ilegales')),
                ('irregular_superfaces', models.IntegerField(verbose_name='Numero de Superficies Irregulares')),
                ('permise_superfaces', models.IntegerField(verbose_name='Numero de Superficies Permisadas')),
                ('regular_superfaces', models.IntegerField(verbose_name='Numero de Superficies regulares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('well_diameter', models.IntegerField(verbose_name='Diametro del Pozo')),
                ('well_deepth', models.IntegerField(verbose_name='Profundidad del Pozo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Well_tracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Well')),
            ],
        ),
        migrations.AddField(
            model_name='lagoon_tracing',
            name='tracing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing'),
        ),
        migrations.AddField(
            model_name='lagoon',
            name='producion_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
        migrations.AddField(
            model_name='cardinal_point',
            name='production_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
    ]
