# Generated by Django 2.1 on 2019-04-18 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardinalPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('north', models.IntegerField(verbose_name='Norte')),
                ('south', models.IntegerField(verbose_name='Sur')),
                ('west', models.IntegerField(verbose_name='Este')),
                ('oest', models.IntegerField(verbose_name='Oeste')),
                ('altitude', models.IntegerField(verbose_name='Altitud')),
                ('total_area_terr', models.IntegerField(verbose_name='Area total del Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lagoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lagoon_diameter', models.IntegerField(verbose_name='Ancho de la Laguna')),
                ('lagoon_deepth', models.IntegerField(verbose_name='Largo de la Laguna ')),
                ('total_area_mirror_guater', models.IntegerField(blank=True, null=True, verbose_name='Area total de Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lagoon_has_especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_specie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LagoonTracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
