# Generated by Django 2.1 on 2019-02-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repre_unit_productive',
            new_name='RepreUnitProductive',
        ),
    ]
