# Generated by Django 2.1 on 2019-01-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardinal_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.IntegerField(verbose_name='Norte')),
                ('south', models.IntegerField(verbose_name='Sur')),
                ('west', models.IntegerField(verbose_name='Este')),
                ('oest', models.IntegerField(verbose_name='Oeste')),
                ('altitude', models.IntegerField(verbose_name='Altitud')),
                ('total_area_terr', models.IntegerField(verbose_name='Area total del Terreno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Production_unit')),
            ],
        ),
    ]
