# Generated by Django 2.1 on 2019-03-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('acuicultura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parish', verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='tracing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing'),
        ),
        migrations.AddField(
            model_name='lagoon_has_especies',
            name='especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Specie'),
        ),
        migrations.AddField(
            model_name='lagoon_has_especies',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoon',
            name='producion_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
        migrations.AddField(
            model_name='cardinalpoint',
            name='production_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
    ]
