# Generated by Django 2.1 on 2019-05-13 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acuicultura', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Company')),
            ],
            bases=('core.company',),
        ),
        migrations.CreateModel(
            name='RepreUnitProductive',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Account')),
            ],
            bases=('core.account',),
        ),
        migrations.CreateModel(
            name='RepreUnitProductiveMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.RepreUnitProductive')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Ordinario')),
                ('scientific_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Cientifico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_lagoon', models.PositiveIntegerField(verbose_name='Numero de Lagunas')),
                ('new_number_lagoon', models.PositiveIntegerField(verbose_name='Numero de Nuevas de Lagunas')),
                ('number_well', models.PositiveIntegerField(verbose_name='Numero de Pozos')),
                ('new_number_well', models.PositiveIntegerField(verbose_name='Numero de  Nuevos Pozos ')),
                ('illegal_superfaces', models.PositiveIntegerField(verbose_name='Numero de Superficies Ilegales')),
                ('permise_superfaces', models.PositiveIntegerField(verbose_name='Numero de Superficies Permisadas')),
                ('regular_superfaces', models.PositiveIntegerField(verbose_name='Numero de Superficies Registradas')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha Del Seguimiento')),
                ('date_next', models.DateField(blank=True, null=True, verbose_name='Fecha Del Siguiente Seguimiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('well_diameter', models.FloatField(verbose_name='Diametro del Pozo')),
                ('well_deepth', models.FloatField(verbose_name='Profundidad del Pozo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
        migrations.CreateModel(
            name='WellTracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Well')),
            ],
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='tracing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing'),
        ),
        migrations.AddField(
            model_name='lagoonespecies',
            name='especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Specie'),
        ),
        migrations.AddField(
            model_name='lagoonespecies',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoon',
            name='producion_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
        migrations.AddField(
            model_name='inspectionlagoon',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='inspectionlagoon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardinalpoint',
            name='production_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
        migrations.AddField(
            model_name='boundarymap',
            name='north',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norte', to='acuicultura.BoundaryMapSelect', verbose_name='Norte'),
        ),
        migrations.AddField(
            model_name='boundarymap',
            name='oest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeste', to='acuicultura.BoundaryMapSelect', verbose_name='Oeste'),
        ),
        migrations.AddField(
            model_name='boundarymap',
            name='south',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sur', to='acuicultura.BoundaryMapSelect', verbose_name='Sur'),
        ),
        migrations.AddField(
            model_name='boundarymap',
            name='west',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='este', to='acuicultura.BoundaryMapSelect', verbose_name='Este'),
        ),
    ]
