# Generated by Django 2.1 on 2019-04-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acuicultura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Company')),
            ],
            bases=('core.company',),
        ),
        migrations.CreateModel(
            name='RepreUnitProductive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_document_repre', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('G', 'G'), ('J', 'J'), ('C', 'C'), ('P', 'P')], max_length=50, verbose_name='Tipo de Documento')),
                ('document_repre', models.CharField(max_length=10, unique=True, verbose_name='Documento')),
                ('name_repre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name_repre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('landline_repre', models.CharField(max_length=11, verbose_name='Telefono Casa')),
                ('phone_repre', models.CharField(max_length=11, verbose_name='Telefono Movil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Ordinario')),
                ('scientific_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Cientifico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_lagoon', models.IntegerField(verbose_name='Numero de Lagunas')),
                ('new_number_lagoon', models.IntegerField(verbose_name='Numero de Nuevas de Lagunas')),
                ('number_well', models.IntegerField(verbose_name='Numero de Pozos')),
                ('new_number_well', models.IntegerField(verbose_name='Numero de  Nuevos Pozos ')),
                ('illegal_superfaces', models.IntegerField(verbose_name='Numero de Superficies Ilegales')),
                ('irregular_superfaces', models.IntegerField(verbose_name='Numero de Superficies Irregulares')),
                ('permise_superfaces', models.IntegerField(verbose_name='Numero de Superficies Permisadas')),
                ('regular_superfaces', models.IntegerField(verbose_name='Numero de Superficies regulares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('well_diameter', models.IntegerField(verbose_name='Diametro del Pozo')),
                ('well_deepth', models.IntegerField(verbose_name='Profundidad del Pozo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
        migrations.CreateModel(
            name='WellTracing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Well')),
            ],
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoontracing',
            name='tracing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Tracing'),
        ),
        migrations.AddField(
            model_name='lagoon_has_especies',
            name='especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Specie'),
        ),
        migrations.AddField(
            model_name='lagoon_has_especies',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
        migrations.AddField(
            model_name='lagoon',
            name='producion_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
        migrations.AddField(
            model_name='cardinalpoint',
            name='production_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
    ]
