# Generated by Django 2.1 on 2019-05-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0002_auto_20190513_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarymap',
            name='production_unit',
            field=models.OneToOneField(default='e989ae06-c2fb-46ab-a02d-cc0bc7ad32ae', on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lagoon',
            name='sistem_cultivate',
            field=models.CharField(blank=True, choices=[('mono', 'Mono Cultivo'), ('duo', 'Poli Cultivo')], max_length=50, null=True, verbose_name='Sistema de Cultivo'),
        ),
    ]
