# Generated by Django 2.1 on 2019-01-20 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acuicultura', '0002_cardinal_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_lagoon', models.IntegerField(verbose_name='Numero de Lagunas')),
                ('new_number_lagoon', models.IntegerField(verbose_name='Numero de Nuevas de Lagunas')),
                ('number_well', models.IntegerField(verbose_name='Numero de Pozos')),
                ('new_number_well', models.IntegerField(verbose_name='Numero de  Nuevos Pozos ')),
                ('illegal_superfaces', models.IntegerField(verbose_name='Numero de Superficies Ilegales')),
                ('irregular_superfaces', models.IntegerField(verbose_name='Numero de Superficies Irregulares')),
                ('permise_superfaces', models.IntegerField(verbose_name='Numero de Superficies Permisadas')),
                ('regular_superfaces', models.IntegerField(verbose_name='Numero de Superficies regulares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producion_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Production_unit')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
