# Generated by Django 2.1 on 2019-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0002_auto_20190429_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinalpoint',
            name='altitude',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='north',
            field=models.FloatField(verbose_name='Norte'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='oest',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Oeste'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='south',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Sur'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='total_area_terr',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Area total del Terreno'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='west',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Este'),
        ),
    ]
