# Generated by Django 2.1 on 2019-04-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0002_auto_20190418_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagoontracing',
            name='sistem_cultivate',
            field=models.CharField(choices=[('is_mono', 'Mono Cultivo'), ('is_duo', 'Duo Cultivo')], default=2, max_length=50, verbose_name='Sistema de Cultivo'),
            preserve_default=False,
        ),
    ]
