# Generated by Django 2.1 on 2019-06-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0002_auto_20190528_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracing',
            name='illegal_superfaces',
        ),
        migrations.RemoveField(
            model_name='tracing',
            name='permise_superfaces',
        ),
        migrations.RemoveField(
            model_name='tracing',
            name='regular_superfaces',
        ),
    ]
