# Generated by Django 2.1 on 2019-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0003_auto_20190430_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinalpoint',
            name='altitude',
            field=models.FloatField(verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='oest',
            field=models.FloatField(verbose_name='Oeste'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='south',
            field=models.FloatField(verbose_name='Sur'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='total_area_terr',
            field=models.FloatField(verbose_name='Area total del Terreno'),
        ),
        migrations.AlterField(
            model_name='cardinalpoint',
            name='west',
            field=models.FloatField(verbose_name='Este'),
        ),
    ]
