# Generated by Django 2.1 on 2019-06-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0003_auto_20190602_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInsopesca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illegal_superfaces', models.BooleanField(verbose_name='Numero de Superficies Ilegales')),
                ('permise_superfaces', models.BooleanField(verbose_name='Numero de Superficies Permisadas')),
                ('regular_superfaces', models.BooleanField(verbose_name='Numero de Superficies Registradas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
            ],
        ),
    ]
