# Generated by Django 2.1 on 2019-02-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0003_auto_20190210_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='Specie',
        ),
    ]
