# Generated by Django 2.1 on 2019-05-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0003_auto_20190514_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinalpoint',
            old_name='north',
            new_name='north_utm',
        ),
        migrations.RenameField(
            model_name='cardinalpoint',
            old_name='west',
            new_name='west_utm',
        ),
    ]
