# Generated by Django 2.1 on 2019-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0004_remove_lagoontracing_sistem_cultivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagoon',
            name='sistem_cultivate',
            field=models.CharField(choices=[('is_mono', 'Mono Cultivo'), ('is_duo', 'Duo Cultivo')], default=2, max_length=50, verbose_name='Sistema de Cultivo'),
            preserve_default=False,
        ),
    ]
