# Generated by Django 2.1 on 2019-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0004_auto_20190514_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionlagoon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inspección'),
        ),
    ]
