# Generated by Django 2.1 on 2019-06-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0004_statusinsopesca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinsopesca',
            name='illegal_superfaces',
            field=models.BooleanField(verbose_name='Superficies Ilegales'),
        ),
        migrations.AlterField(
            model_name='statusinsopesca',
            name='permise_superfaces',
            field=models.BooleanField(verbose_name='Superficies Permisadas'),
        ),
        migrations.AlterField(
            model_name='statusinsopesca',
            name='regular_superfaces',
            field=models.BooleanField(verbose_name='Superficies Registradas'),
        ),
    ]
