# Generated by Django 2.1 on 2019-01-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0005_lagoon_tracing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repre_unit_productive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document_repre', models.CharField(choices=[('CEDULA', 'CEDULA'), ('PASAPORTE', 'PASAPORTE'), ('RIF', 'RIF')], max_length=50, verbose_name='Tipo de Documento')),
                ('document_repre', models.CharField(max_length=10, verbose_name='Documento')),
                ('name_repre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name_repre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('landline_repre', models.CharField(max_length=11, verbose_name='Telefono Fijo')),
                ('phone_repre', models.CharField(max_length=11, verbose_name='Telefono Movil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Production_unit')),
            ],
        ),
    ]
