# Generated by Django 2.1 on 2019-04-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0005_auto_20190430_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='ordinary_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Ordinario'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Cientifico'),
        ),
    ]
