# Generated by Django 2.1 on 2019-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0005_lagoon_sistem_cultivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagoon',
            name='sistem_cultivate',
            field=models.CharField(blank=True, choices=[('is_mono', 'Mono Cultivo'), ('is_duo', 'Duo Cultivo')], max_length=50, null=True, verbose_name='Sistema de Cultivo'),
        ),
    ]
