# Generated by Django 2.1 on 2019-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0005_auto_20190211_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='repreunitproductive',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Es Activo'),
        ),
        migrations.AlterField(
            model_name='repreunitproductive',
            name='landline_repre',
            field=models.CharField(max_length=11, verbose_name='Telefono Casa'),
        ),
    ]
