# Generated by Django 2.1 on 2019-02-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0006_auto_20190211_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repreunitproductive',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit'),
        ),
    ]
