# Generated by Django 2.1 on 2019-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0006_auto_20190430_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagoon',
            name='lagoon_deepth',
            field=models.FloatField(verbose_name='Largo de la Laguna '),
        ),
        migrations.AlterField(
            model_name='lagoon',
            name='lagoon_diameter',
            field=models.FloatField(verbose_name='Ancho de la Laguna'),
        ),
        migrations.AlterField(
            model_name='lagoon',
            name='total_area_mirror_guater',
            field=models.FloatField(blank=True, null=True, verbose_name='Area total de Terreno'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_deepth',
            field=models.FloatField(verbose_name='Profundidad del Pozo'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_diameter',
            field=models.FloatField(verbose_name='Diametro del Pozo'),
        ),
    ]
