# Generated by Django 2.1 on 2019-05-11 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acuicultura', '0007_auto_20190430_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionLagoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxdi', models.FloatField(verbose_name='OXIGENO DISUELTO (mg/l)')),
                ('saox', models.FloatField(verbose_name='% SATURACION DE OXIGENO')),
                ('ph', models.FloatField(verbose_name='PH')),
                ('conde', models.FloatField(verbose_name='CONDUCTIVILIDAD ELECTRICA')),
                ('soto', models.FloatField(verbose_name='SOLIDOS TOTALES')),
                ('sotodi', models.FloatField(verbose_name='SOLIDOS TOTALES DISUELTOS (mg/l)')),
                ('trans', models.FloatField(verbose_name='TRANSPARENCIA (cm)')),
                ('tempa', models.FloatField(verbose_name='TEMPERATURA DEL AGUA (ºC)')),
                ('odsa', models.FloatField(verbose_name='O.D. AL 100% DE SATURACION')),
                ('notes', models.TextField(verbose_name='Observaciones')),
                ('date', models.DateField(verbose_name='Fecha de Inspección')),
                ('next_date', models.DateField(verbose_name='Siguiente Inspección')),
                ('lagoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
