# Generated by Django 2.1 on 2019-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0007_production_unit_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_unit',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono Movil'),
        ),
    ]
