# Generated by Django 2.1 on 2019-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0008_auto_20190218_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
