# Generated by Django 2.1 on 2019-05-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0008_inspectionlagoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagoonespecies',
            name='number_specie',
            field=models.FloatField(),
        ),
    ]
