# Generated by Django 2.1 on 2019-05-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0009_auto_20190512_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepreUnitProductiveMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.ProductionUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.RepreUnitProductive')),
            ],
        ),
    ]
