# Generated by Django 2.1 on 2019-02-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0009_production_unit_operative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_unit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
