# Generated by Django 2.1 on 2019-02-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0009_auto_20190226_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagoon_has_especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_specie', models.IntegerField()),
                ('especies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Specie')),
            ],
        ),
        migrations.AlterField(
            model_name='lagoon',
            name='lagoon_deepth',
            field=models.IntegerField(verbose_name='Largo de la Laguna '),
        ),
        migrations.AlterField(
            model_name='lagoon',
            name='lagoon_diameter',
            field=models.IntegerField(verbose_name='Ancho de la Laguna'),
        ),
        migrations.AddField(
            model_name='lagoon_has_especies',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acuicultura.Lagoon'),
        ),
    ]
