# Generated by Django 2.1 on 2019-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0010_auto_20190208_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repre_unit_productive',
            name='document_repre',
            field=models.CharField(max_length=10, unique=True, verbose_name='Documento'),
        ),
    ]
