# Generated by Django 2.1 on 2019-05-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0010_repreunitproductivemany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repreunitproductive',
            name='production_unit',
        ),
    ]
