# Generated by Django 2.1 on 2019-02-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0011_auto_20190208_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cardinal_points',
            new_name='Cardinal_point',
        ),
    ]
