# Generated by Django 2.1 on 2019-02-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuicultura', '0012_auto_20190208_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_unit',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
