# Generated by Django 2.1 on 2018-12-14 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ci', models.CharField(max_length=8, verbose_name='Cedula')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electronico')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uuid')),
                ('change_pass', models.BooleanField(default=False, verbose_name='Cambio La Contraseña')),
                ('question', models.BooleanField(default=False, verbose_name='Completo Sus Preguntas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es Super Usuario')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('role', models.CharField(blank=True, choices=[('is_coordinator', 'Coordinador'), ('is_worker', 'Trabajador')], max_length=500, null=True, verbose_name='Rol')),
                ('level', models.CharField(blank=True, choices=[('is_ord_pesque', 'Ordenación Pesquera'), ('is_acuicul', 'Acuicultura')], max_length=50, null=True, verbose_name='Level')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Unido Desde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ('-created_at',),
            },
        ),
    ]
