# Generated by Django 2.1 on 2019-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ip',
            field=models.CharField(default=1, max_length=20, verbose_name='Direccion IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(default=1, max_length=20, verbose_name='Direccion IP'),
            preserve_default=False,
        ),
    ]
