# Generated by Django 2.1 on 2019-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190420_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_login',
            field=models.BooleanField(default=False, verbose_name='Tiene Una Sesion Activa'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_login',
            field=models.BooleanField(default=False, verbose_name='Tiene Una Sesion Activa'),
        ),
    ]
