# Generated by Django 2.1 on 2019-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_historicalsecurityquestion_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='level',
            field=models.CharField(blank=True, choices=[('is_ord_pesque', 'Ordenación Pesquera'), ('is_acuicul', 'Acuicultura'), ('is_sanid', 'Sanidad'), ('is_tvc', 'Tramitación Vigilancia y Control'), ('is_fomen', 'Fomento Pesquero y Acuicola')], max_length=50, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('is_ord_pesque', 'Ordenación Pesquera'), ('is_acuicul', 'Acuicultura'), ('is_sanid', 'Sanidad'), ('is_tvc', 'Tramitación Vigilancia y Control'), ('is_fomen', 'Fomento Pesquero y Acuicola')], max_length=50, null=True, verbose_name='Level'),
        ),
    ]
