# Generated by Django 2.1 on 2019-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190209_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='ci',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=8, unique=True, verbose_name='Cedula'),
        ),
    ]
