import "./scss/index.scss"

import "./module/location.js"
import "./module/user_register.js"
import "./module/profile_user.js"
import "./module/forgot_password.js"
import "./module/tracing_form.js"
import "./module/sanidad/account_form.js"
import "./module/sanidad/company_form.js"
import "./module/sanidad/inspection.js"
