import "./scss/index.scss"
import '@fullcalendar/core/main.css';
import '@fullcalendar/daygrid/main.css';
import '@fullcalendar/timegrid/main.css';
import '@fullcalendar/list/main.css';

import "./module/location.js"
import "./module/user_register.js"
import "./module/profile_user.js"
import "./module/forgot_password.js"
import "./module/acuicultura/tracing_form.js"
import "./module/acuicultura/company_form.js"
import "./module/acuicultura/species_form.js"
import "./module/acuicultura/repre_form.js"
import "./module/acuicultura/specie.js"
import "./module/sanidad/account_form.js"
import "./module/sanidad/company_form.js"
import "./module/sanidad/inspection.js"
import "./module/sanidad/driver.js"
import "./module/sanidad/dashboard.js"
import "./module/sanidad/transport.js"
